#!/usr/bin/env bash


# create accounts
cleos create account eosio ochre EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM
cleos create account eosio user EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM
cleos create account eosio p1 EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM
cleos create account eosio p2 EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM
cleos create account eosio p3 EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM EOS88FhBenkNsFxRxBvYNzS75JCbxMWFaykkQz42Shc7kijnydmZM